name: Convert MP4 to GIFs

on:
  push:
    branches:
      - final-videos
    paths:
      - 'samp-animations/**'

jobs:
  convert-to-gif:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v3
        id: setup-ffmpeg
        with:
          ffmpeg-version: release

      - name: Create GIF output folder
        run: |
          New-Item -ItemType Directory -Force -Path samp-animation-gifs
        shell: powershell

      - name: Run conversion script
        run: ./convert-gif.ps1
        shell: powershell

      - name: Commit GIFs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add samp-animation-gifs
          git diff-index --quiet HEAD || git commit -m "Add generated GIFs [skip ci]"
          git push
        shell: powershell
